# Step 1
welcome-header:
  'Welcome to the System Support Map (SSM) wizard'
welcome-text.paras:
  - 'A System Support Map (SSM) is a way of visualizing the different kinds of support you might use to work on a complicated challenge.'
  - 'For example, a map for a mother of a child with special healthcare needs would include her responsibilities to her child, what she needs to do to fulfill those responsibilities, and the resources that help her meet those needs. Check the sidebar for some more examples of systems mapped by others.'
  - 'This wizard will ask you questions and then build the System Support Map for you based on your answers.'
  - 'Hit the &ldquo;Next&rdquo; button to continue.'
example-systems-header:
  'Examples of systems mapped by SSM'
example-systems.list:
  - 'Supporting a child/children with special health care needs and/or developmental disabilities;'
  - 'Above, but in a specific life-course (i.e., transition to adulthood);'
  - 'Family outcomes in the 3 months post-partum;'
  - 'The social-emotional health of a child/children;'
  - 'Migraine self-management;'
  - 'Community-academic partnerships working to improve population health;'
  - 'Efforts to address isolation among individuals in a community;'
  - 'Efforts to increase inter-generational cohesion in a community;'
  - 'And, efforts to reconnect with one’s landscape/environment.'

# Step 2
overview-header: 'Overview'
overview-text.paras:
  - 'Here&rsquo;s a quick overview of the process.'
  - 'Notice the rings in the chart below and the labels for each ring.'
  - 'You will build your SSM step-by-step, starting inside the innermost ring and working your way outwards.'
  - 'The controls in the lower left corner may be used to build a System Support Map directly, but this wizard is intended to do the building for you.'
  - 'Hit the &ldquo;Next&rdquo; button to continue.'

# Step 3
prerequisites-header: 'Prerequisites'
prerequisites-text.paras:
  - 'Before starting to build your SSM, you should have a clear idea of the challenge you are attempting to map and your role in it.'
  - 'This is important! If you don&rsquo;t have a solid understanding of your role in this challenge, this exercise could be unclear and unhelpful.'
  - 'Hit the &ldquo;Next&rdquo; button to continue.'

# Step 4
ring1-header: 'Ring #1: Identifying Your Role'
ring1-intro.paras:
  - 'What role do you play in the system producing this challenge? Some possible roles are: patient, family member, teacher, organizational leader, legislator, or community member.'
  - 'If you have multiple roles that you want to study, pick one. Each map is for one role, and one role only. You can come back and fill out other maps for other roles later, if you want.'
ring1-label: 'My role is:'
ring1-afterword.paras:
  - 'When you hit &ldquo;Next,&rdquo; your role will be inserted into the chart below for you.'
  - 'Hit the &ldquo;Next&rdquo; button to continue.'

# Step 5
ring2-header: 'Ring #2: Responsibilities'
ring2-aside:
  'Tip: For some people it makes more sense to describe objectives or goals instead of responsibilities in the second ring.'
# Note: this must include a <span> with id "wizard_role_text" somewhere.
ring2-text.paras:
  - 'The second ring contains the responsibilities that you have in your role as a(n) <code><span id="wizard_role_text">_</span></code>.'
  - 'Identify the four to eight most important responsibilities and add them here.'
  - 'When you click the &ldquo;Add&rdquo; button below, the responsibilities you&rsquo;ve entered will be added to the chart below. After that you can add other responsibilities, or click the &ldquo;Next&rdquo; button to go to the next step.'
  - 'I have a responsibility to:'

# Step 6
ring3-header: 'Ring #3: Needs'
ring3-text.paras:
  - 'The third ring identifies exactly what is needed to meet each responsibility. Common responses include time, money, reimbursement, buy-in from my organization, and information. Please be creative here! The more comprehensive this list is the better. Be sure to consider personal needs, like patience, empathy, energy, and creativity.'
  - 'You&rsquo;ll be asked about each responsibility in turn, starting with the first one you entered.'
ring3-prompt.paras:
  - 'To fulfill this responsibility, I need:'

# Step 7
pre-ring4-text.paras:
  - 'Here&rsquo;s your map so far.'
  - 'Please gather your thoughts about resources that you have tried in the recent past.'

# Step 8
ring4-header: 'Ring #4: Resources'
ring4-aside:
  'Tip: If needs were ingredients in a recipe, resources might include things like a favorite recipe, particular brands of an ingredient, or a store that sells many ingredients on your list.'
ring4-intro.paras:
  - 'The next ring identifies the resources you use to meet your needs from Ring #3. Reflect for a moment about the needs you listed. What specific things, organizations, places, or people have you tried (whether or not they have helped you) to get that need met? Resources for your map might include websites, brochures, training programs, buses, providers, a case manager, organizations in your community, or books you read to build a skill in yourself.'
  - 'The lines to resources on Ring #4 will be color-coded to indicate their level of helpfulness.'
ring4-resource-type-prompt:
  'What type of resource would you like to describe?'
ring4-resource-name-prompt:
  'Can you name/describe the resource more specifically?'
ring4-resource-label-field-before-prompt: 'Use the'
ring4-resource-label-field-after-prompt: 'for the label in the map below.'
ring4-resource-needs-prompt:
  'Please select all needs that you have entered that this resource supports.'
ring4-resource-helpfulness-prompt:
  'How helpful has this resource been?'
ring4-resource-helpfulness-description-prompt:
  'Can you describe why you feel the resource is or is not helpful? In what ways?'

# Resource interstitial
ring4-interstitial-text.paras:
  - 'Here&rsquo;s your map so far.'
  - 'If you&rsquo;d like to add another resource, click the &ldquo;Add Resource&rdquo; button. Otherwise, click &ldquo;Next&rdquo;.'

# Step 9
pre-ring5-text.paras:
  - 'Please reflect on your map and consider your wishes. If you could have anything, what might better support you in meeting your responsibilities?'
  - 'The next steps will guide you through entering your top 3 wishes, one at a time.'

# Step 10
ring5-header: 'Outer area: Wishes'
# Note: this must contain a span of class "wish-number":
ring5-intro.paras:
  - 'If you could have anything to support you in your responsibilities, what would it be? These wishes will go outside of the outermost ring. We&rsquo;ll do 3 wishes. You&rsquo;re currently on wish <span class="wish-number"></span> of 3.'
ring5-wish-name-prompt:
  'Please describe your wish.'
ring5-wish-connection-prompt:
  'Does it connect most importantly to:'
ring5-wish-connection-responsibility:
  'a responsibility you feel stuck on;'
ring5-wish-connection-need:
  'a need you struggle to meet;'
ring5-wish-connection-resource:
  'or a resource that you would like to change in some way?'
# Note: this must contain a span of class "wish-parent-type":
ring5-wish-parent-text.paras:
  - '(Note: we want to connect your wish to the one most important factor in your map.) Please select the specific <span class="wish-parent-type"></span> from the list below.'
ring5-wish-resource-description-prompt:
  'Please describe how you would like that resource to change.'

# Step 11
review-header: 'Review and Next Steps'
review-aside-header: 'Wondering what to do next?'
review-aside-text.paras:
  - 'Now that you have a clear picture of the challenge and your role in it, many people find it helpful to use the map to think about how they could work on the challenge. What could you do to change your role, responsibilities, resources, and needs for the better? You can add these wishes on the outside of the rings, connecting them with the responsibilities, needs, or resources they would change.'
review-text.paras:
  - 'You&rsquo;re done! When you click the &ldquo;Finish&rdquo; button, this guide will go away and you can view or print your map.'
review-download-prompt: 'You can also:'
review-download-data-text: 'download your map data'
review-download-image-text: 'download your map as an image'
